# Tutorial to use with: https://github.com/andry81-devops/github-action-extensions
#

name: git-checkout-extension
description: 'GitHub composite action extension of `actions/checkout` action'

branding:
  icon:  upload
  color: purple

inputs:
  # CAUTION:
  #   The `inputs` is derived from the https://github.com/actions/checkout action script.
  #
  repository:
    default: ${{ github.repository }}
  ref:
    required: false
  token:
    default: ${{ github.token }}
  ssh-key:
    required: false
  ssh-known-hosts:
    required: false
  ssh-strict:
    default: true
  persist-credentials:
    default: true
  path:
    required: false
  clean:
    default: true
  fetch-depth:
    default: 1
  lfs:
    default: false
  submodules:
    default: false
  set-safe-directory:
    default: true
  github-server-url:
    required: false

  # available: v3 | v2
  actions--checkout-ref:
    required: false
    default: v3

  mkdir-p:
    default: ''

runs:
  using: "composite"
  steps:
    - name: '[git-checkout-extension][01] check repository on existence and has a branch reference: `${{ inputs.repository }}`'
      id: check-repo-exists-and-has-ref
      #continue-on-error: true
      shell: bash
      run: |
        ### [git-checkout-extension][01] check repository on existence and has a branch reference: `${{ inputs.repository }}`
        # CAUTION: must be with a token, otherwise will fail on a private repository
        if [[ -n "${{ inputs.ref }}" ]]; then
          git ls-remote -q --exit-code "https://${{ inputs.token }}@github.com/${{ inputs.repository }}" "${{ inputs.ref }}" > /dev/null 2>&1
        else
          git ls-remote -q --exit-code "https://${{ inputs.token }}@github.com/${{ inputs.repository }}" > /dev/null 2>&1
        fi
        if (( ! $? )); then
          echo "is-repo-exists-and-has-ref=true" >> "$GITHUB_OUTPUT"
        else
          echo "is-repo-exists-and-has-ref=false" >> "$GITHUB_OUTPUT"
        fi

    # CAUTION:
    #
    #   Use copmarison with the string in the `if` expression to temporary workaround the issue:
    #
    #   `Boolean inputs are not actually booleans` : https://github.com/actions/runner/issues/1483
    #

    - name: "[git-checkout-extension][02] if: ${{ (steps.check-repo-exists-and-has-ref.outputs.is-repo-exists-and-has-ref == 'true') && (inputs.actions--checkout-ref == 'v3') }}"
      #if: ${{ steps.check-repo-exists-and-has-ref.conclusion == 'success' }}
      if: ${{ (steps.check-repo-exists-and-has-ref.outputs.is-repo-exists-and-has-ref == 'true') && (inputs.actions--checkout-ref == 'v3') }}
      uses: actions/checkout@v3
      with:
        repository:           ${{ inputs.repository }}
        ref:                  ${{ inputs.ref }}
        token:                ${{ inputs.token }}
        ssh-key:              ${{ inputs.ssh-key }}
        ssh-known-hosts:      ${{ inputs.ssh-known-hosts }}
        ssh-strict:           ${{ inputs.ssh-strict }}
        persist-credentials:  ${{ inputs.persist-credentials }}
        path:                 ${{ inputs.path }}
        clean:                ${{ inputs.clean }}
        fetch-depth:          ${{ inputs.fetch-depth }}
        lfs:                  ${{ inputs.lfs }}
        submodules:           ${{ inputs.submodules }}
        set-safe-directory:   ${{ inputs.set-safe-directory }}
        github-server-url:    ${{ inputs.github-server-url }}

    - name: "[git-checkout-extension][03] if: ${{ (steps.check-repo-exists-and-has-ref.outputs.is-repo-exists-and-has-ref == 'true') && (inputs.actions--checkout-ref == 'v2') }}"
      if: ${{ (steps.check-repo-exists-and-has-ref.outputs.is-repo-exists-and-has-ref == 'true') && (inputs.actions--checkout-ref == 'v2') }}
      uses: actions/checkout@v2
      with:
        repository:           ${{ inputs.repository }}
        ref:                  ${{ inputs.ref }}
        token:                ${{ inputs.token }}
        ssh-key:              ${{ inputs.ssh-key }}
        ssh-known-hosts:      ${{ inputs.ssh-known-hosts }}
        ssh-strict:           ${{ inputs.ssh-strict }}
        persist-credentials:  ${{ inputs.persist-credentials }}
        path:                 ${{ inputs.path }}
        clean:                ${{ inputs.clean }}
        fetch-depth:          ${{ inputs.fetch-depth }}
        lfs:                  ${{ inputs.lfs }}
        submodules:           ${{ inputs.submodules }}
        set-safe-directory:   ${{ inputs.set-safe-directory }}

    - name: '[git-checkout-extension][04] working copy initialization: `${{ inputs.path }}`'
      #if: ${{ steps.check-repo-exists-and-has-ref.conclusion != 'success' }}
      if: ${{ steps.check-repo-exists-and-has-ref.outputs.is-repo-exists-and-has-ref != 'true' }}
      shell: bash
      run: |
        ### [git-checkout-extension][04] working copy initialization: `${{ inputs.path }}`
        inputs_path='${{ inputs.path }}'
        function call()
        {
          echo ">$@"
          "$@"
        }
        if [[ ! -e "$GITHUB_WORKSPACE${inputs_path:+/}$inputs_path" ]]; then
          call mkdir -p "$GITHUB_WORKSPACE${inputs_path:+/}$inputs_path" || exit
        fi
        if [[ ! -e "$GITHUB_WORKSPACE${inputs_path:+/}$inputs_path/.git" ]]; then
          call pushd "$GITHUB_WORKSPACE${inputs_path:+/}$inputs_path" && {
            call git init || exit
            call git remote add origin "https://github.com/${{ inputs.repository }}" || exit
            if [[ -n "${{ inputs.ref }}" ]]; then
              call git branch -m "${{ inputs.ref }}" || exit
            fi
            call popd
          }
        fi

    - name: '[git-checkout-extension][05] working copy directories allocation'
      if: ${{ inputs.mkdir-p != '' }}
      shell: bash
      run: |
        ### [git-checkout-extension][05] working copy directories allocation
        inputs_mkdir_p=(${{ inputs.mkdir-p }})
        inputs_path='${{ inputs.path }}'
        function call()
        {
          echo ">$@"
          "$@"
        }
        call pushd "$GITHUB_WORKSPACE${inputs_path:+/}$inputs_path" && {
          for arg in "${inputs_mkdir_p[@]}"; do
            if [[ ! -e "$arg" ]]; then
              call mkdir -p "$arg" || exit
            fi
          done
          call popd
        }
